"""SKILL.md generator — converts WorkprintProfile into executable Claude ​Code skill."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from workprint.models import (
    BehaviorPattern,
    ConfidenceLevel,
    WorkflowPattern,
    WorkprintProfile,
)

_CONFIDENCE_EMOJI = {
    ConfidenceLevel.HIGH: "●",
    ConfidenceLevel.MEDIUM: "◑",
    ConfidenceLevel.LOW: "○",
}

_CONFIDENCE_LABEL = {
    ConfidenceLevel.HIGH: "High",
    ConfidenceLevel.MEDIUM: "Medium",
    ConfidenceLevel.LOW: "Low",
}


class SkillGenerator:
    """Renders a WorkprintProfile as a SKILL.md string."""

    def __init__(self, profile: WorkprintProfile):
        self.profile = profile

    # ------------------------------------------------------------------
    def render(self) -> str:
        sections = [
            self._frontmatter(),
            self._header(),
            self._usage(),
            self._behavioral_dna(),
            self._core_patterns(),
            self._workflow_patterns(),
            self._anti_patterns(),
            self._honest_limits(),
            self._footer(),
        ]
        return "\n\n".join(s for s in sections if s.strip())

    def write(self, path: Path) -> None:
        path.write_text(self.render(), encoding="utf-8")

    # ------------------------------------------------------------------
    def _frontmatter(self) -> str:
        p = self.profile
        return f"""---
name: workprint/{p.name}
description: Behavioral skill distilled from {p.total_traces} real traces ({p.date_range})
version: 0.1.0
distilled_at: {datetime.now().strftime("%Y-%m-%d")}
total_traces: {p.total_traces}
---"""

    def _header(self) -> str:
        p = self.profile
        return f"""# Workprint: {p.display_name}

> Distilled from **{p.total_traces}** behavioral traces across {p.date_range}

This skill is generated by [Workprint](https://github.com/workprint/workprint) from real behavioral traces—not self-reports, not inferred personality. Every pattern below is backed by empirical evidence from what {p.display_name} actually did."""

    def _usage(self) -> str:
        p = self.profile
        slug = p.name
        return f"""## Usage

```
/workprint {slug} review this PR for me
/workprint {slug} how would you approach this architecture decision?
/workprint {slug} write a commit message for these changes
```

When activated, this skill instructs Claude to respond from the perspective of {p.display_name}'s actual working patterns—using observed behavioral evidence, not role-play assumptions."""

    def _behavioral_dna(self) -> str:
        p = self.profile
        lines = ["## Behavioral DNA\n"]

        if p.tool_preferences:
            top = sorted(p.tool_preferences.items(), key=lambda x: -x[1])
            tools_str = ", ".join(f"`{k}` ({v})" for k, v in top[:6])
            lines.append(f"**Most-used tools**: {tools_str}\n")

        if p.language_preferences:
            top = sorted(p.language_preferences.items(), key=lambda x: -x[1])
            total = sum(v for _, v in top)
            lang_parts = [f"{k} ({int(100*v/total)}%)" for k, v in top[:4]]
            lines.append(f"**Language mix**: {', '.join(lang_parts)}\n")

        if p.style_notes:
            lines.append("**Working style notes**:")
            for note in p.style_notes:
                lines.append(f"- {note}")

        return "\n".join(lines)

    def _core_patterns(self) -> str:
        patterns = self.profile.behavioral_patterns
        if not patterns:
            return ""

        lines = ["## Core Behavioral Patterns\n"]
        lines.append(
            "_Legend: ● High confidence | ◑ Medium | ○ Low — based on evidence count_\n"
        )

        for p in patterns:
            lines.append(self._render_pattern(p))

        return "\n".join(lines)

    def _workflow_patterns(self) -> str:
        workflows = self.profile.workflows
        if not workflows:
            return ""

        lines = ["## Workflow Patterns\n"]
        lines.append("_Sequences that appear repeatedly in behavioral traces._\n")

        for w in workflows:
            conf_icon = _CONFIDENCE_EMOJI.get(w.confidence, "○")
            steps_str = " → ".join(f"`{s}`" for s in w.steps)
            lines.append(f"### {conf_icon} {w.name}")
            lines.append(f"**Sequence**: {steps_str}  ")
            lines.append(f"**Occurrences**: {w.occurrence_count}\n")
            lines.append(f"{w.description}\n")
            if w.triggers:
                lines.append("**Triggers**:")
                for trigger in w.triggers:
                    lines.append(f"- {trigger}")
            lines.append("---")

        return "\n".join(lines)

    def _anti_patterns(self) -> str:
        ap = self.profile.anti_patterns
        if not ap:
            return ""

        lines = ["## Anti-Patterns\n"]
        lines.append("_Behaviors consistently absent from the traces — things this person avoids._\n")

        for p in ap:
            lines.append(f"### {p.name}")
            lines.append(f"{p.description}")
            if p.evidence:
                lines.append("\n**Context**:")
                for e in p.evidence[:3]:
                    lines.append(e.format())
            lines.append("")

        return "\n".join(lines)

    def _honest_limits(self) -> str:
        p = self.profile
        default_limits = [
            "This skill reflects **observed patterns**, not complete personality. "
            "Actual reasoning and intuition cannot be fully captured from traces.",
            "Patterns are derived from a specific time window. "
            "Behavior may have shifted since the traces were collected.",
            "Private decisions and thought processes are not in the data—"
            "only actions that left a trace are included.",
        ]
        limits = p.honest_limits if p.honest_limits else default_limits

        lines = ["## Honest Limits\n"]
        lines.append("_What this workprint cannot replicate:_\n")
        for limit in limits:
            lines.append(f"- {limit}")
        return "\n".join(lines)

    def _footer(self) -> str:
        return (
            "---\n\n"
            "_Generated by [Workprint](https://github.com/workprint/workprint) — "
            "Distill real behavior traces into executable AI skills._"
        )

    # ------------------------------------------------------------------
    @staticmethod
    def _render_pattern(p: BehaviorPattern) -> str:
        conf_icon = _CONFIDENCE_EMOJI.get(p.confidence, "○")
        conf_label = _CONFIDENCE_LABEL.get(p.confidence, "Low")
        lines = [
            f"### {conf_icon} {p.name}",
            f"**Type**: `{p.pattern_type}` | "
            f"**Confidence**: {conf_label} | "
            f"**Evidence**: {p.evidence_count} occurrences",
        ]
        if p.date_range != "unknown":
            lines.append(f"**Period**: {p.date_range}\n")
        else:
            lines.append("")
        lines.append(p.description)
        if p.evidence:
            lines.append("\n**Behavioral evidence**:")
            for e in p.evidence[:5]:
                lines.append(e.format())
        if p.tags:
            lines.append(f"\n_Tags: {', '.join(p.tags)}_")
        lines.append("\n---")
        return "\n".join(lines)
